server:
  port: 9007
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: fastfeign
  jackson:
    serialization:
      indent-output: true
feign:
  hystrix:
    enabled: true