server:
  port: 9001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: fastserver