server:
  port: 9003
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9001/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: fastusertest
  jackson:
    serialization:
      indent-output: true